//
// Created by Кежик Кызыл-оол on 2019-04-10.
//

#ifndef TANCHIKI_WIDGETS_NAMES_HPP
#define TANCHIKI_WIDGETS_NAMES_HPP

const char* WIDGETS_MAIN_MENU = "WIDGETS_MAIN_MENU";
const char* WIDGETS_LOGIN = "WIDGETS_LOGIN";
const char* WIDGETS_ENTER_NAME = "WIDGETS_ENTER_NAME";
const char* WIDGETS_CHOOSE_MAP = "WIDGETS_CHOOSE_MAP";
const char* WIDGETS_CREATING_MATCH = "WIDGETS_CREATING_MATCH";
const char* WIDGETS_CONFIRM = "WIDGETS_CONFIRM";

#endif //TANCHIKI_WIDGETS_NAMES_HPP
